package token

var Names = map[TokenType]string{
	ILLEGAL:   "ILLEGAL",
	EOF:       "EOF",
	ID:        "ID",
	LE:        "LE",
	GE:        "GE",
	LT:        "LT",
	GT:        "GT",
	EQ:        "EQ",
	NE:        "NE",
	INT:       "INT",
	ASSIGN:    "ASSIGN",
	PLUS:      "PLUS",
	MINUS:     "MINUS",
	BANG:      "BANG",
	ASTERISK:  "ASTERISK",
	SLASH:     "SLASH",
	BACKSLASH: "BACKSLASH",
	COMMA:     "COMMA",
	SEMICOLON: "SEMICOLON",
	LPAREN:    "LPAREN",
	RPAREN:    "RPAREN",
	LBRACE:    "LBRACE",
	RBRACE:    "RBRACE",
	SPACE:     "SPACE",
	EOL:       "EOL",
	FUNCTION:  "FUNCTION",
	LET:       "LET",
	TRUE:      "TRUE",
	FALSE:     "FALSE",
	IF:        "IF",
	ELSE:      "ELSE",
	RETURN:    "RETURN",
}
